name: 'action-packipk'
description: 'Packs control as well as data directories into an .ipk file and optionally creates a signed opkg repository.'
author: "resmh"
inputs:
  input:
    description: 'Package input folder'
    required: true
    default: '.'
  output:
    description: 'Package output folder'
    required: true
    default: '.'
  timestamp:
    description: 'Update package control SourceDateEpoch field to current time'
    required: false
    default: ''
  timestamp_patch:
    description: 'Update package control Version patch field to current time'
    required: false
    default: ''
runs:
  using: 'node18'
  main: 'start.js'
branding:
  icon: 'arrow-up-circle'
  color: 'green'
